### ISSUE TITLE
"Parsing the package" problem before installing Revanced

### ISSUE THREAD

**Issue by xeophyte** [revancedapps/revanced.net#12]
Hi, on the newest version 19.04.37 and also on other older like 18.19.35 I have this "Parsing the package" info before even installing Revanced on my android 7.1.2. What can be the reason? I don't have any other vanced/revanced/YT installed.

**Comment by revancedapps** [comment]
I'm not sure either, try using an APK installer tool like https://play.google.com/store/apps/details?id=com.aefyr.sai, then install the APK and see how it goes. If there are errors, it will return more detailed errors. Please take a screenshot of it for me to see.

**Comment by revancedapps** [comment]
Hi, some of the new patches might not work on Android 7, so downloading the pre-patched APK could lead to certain installation issues. 
I recommend downloading the APK manager yourself at https://github.com/ReVanced/revanced-manager/releases/download/v1.18.0/revanced-manager-v1.18.0.apk and then patching it using your device. This might be a better solution. 
Soon, I am planning on building another APK to support older Android devices running Android 5 to Android 7.

**Comment by xeophyte** [comment]
I can't install revanced-manager-v1.18.0.apk because of the same error.
I did install revanced.net_revanced_manager_v1.9.11.apk and it worked, but it downloads YouTube ReVanced that doesn't work.

**Comment by revancedapps** [comment]
Yeah, it's a bug when you are using Android 7. You can try with an older version from https://revanced.net/youtube-revanced#other-versions

**Comment by xeophyte** [comment]
So, can this be fixed?

**Comment by revancedapps** [comment]
Unfortunately, this is the only way. If none of the versions can be installed, then this issue might not be fixable on your device. Another perspective: could MIUI have blocked the installation?

**Comment by xeophyte** [comment]
I don't know what in my MIUI can block this, I rather have everything unlocked.
So, what is the minimum android version to not have this bug?

**Comment by revancedapps** [comment]
Hi, please try with this version: https://revanced.net/revanced-youtube-extended-for-android-6-android-7

**Comment by xeophyte** [comment]
It's working, thanks. Will this version be supported in the future?

**Comment by revancedapps** [comment]
yes, this version will be updated in the future.
