### ISSUE TITLE
No gmscore download option in the manager ?

### ISSUE THREAD

**Issue by soulnous** [revancedapps/revanced.net#16]
In the latest update of the YouTube revanced in your app manager so that apk of the latest YouTube revanced asks for gmscore to make the YouTube running 
Can you edit to another YouTube revanced that doesn't need gmscore and it'll keep use the Microg or from now all of the new revanced YouTube's will need gmscore ? Thanks

**Comment by revancedapps** [comment]
I have attempted to build a version without GmsCore, but it seems that Youtube ReVanced operates unstably after a few videos. Hence, I recommend installing the latest version of GmsCore for the best user experience with Youtube ReVanced.

**Comment by soulnous** [comment]
Well , thanks a lot for your comment ! 2. There's any telegram group that you own? If yes I would like to join !
3. Can you add the gmscore apk into your app manager ? So it'll be easier to download and install the gmscore (same as there's an option in your manager to install the Microg for example)
Thanks !

**Comment by revancedapps** [comment]
GmsCore is also known as MicroG or mMicroG, with ReVanced users more familiar with the term MicroG. For this reason, I use the name MicroG as it appears clearer and more relatable to non-tech-savvy individuals. 
![image](https://github.com/revancedapps/revanced.net/assets/134407424/6cbe26fb-e1ed-42c7-9237-76f4a035ebae)

Regarding the Telegram groups, I don't have my own channel, but I participate and stay updated in the following channels where there are discussions about bugs and suggestions for new builds:
https://t.me/app_revanced
https://t.me/revancifychat
https://t.me/revanced_extended_chat
https://t.me/rvx_lite
https://t.me/ReXgroups
https://t.me/ReVanced_MMT

**Comment by soulnous** [comment]
Thanks a lot for your answer I appreciate that !
Any chance that you can send me a message in the telegram please ? 
@soulnous
I'm using your manager since you released it in your website 
Send me a message please ❤️🙏🏿
