### ISSUE TITLE
how to use duolingo Super Duolingo Unlocked？

### ISSUE THREAD

**Issue by syymo** [revancedapps/revanced.net#19]
I have installed the website to provide APK, but after logging in to my account, I still haven't unlocked the unlimited hearts
![Screenshot_2024-04-10-09-24-52-33_c758632aec9121954782a375cb59c81d](https://github.com/revancedapps/revanced.net/assets/26571594/7d72b503-26eb-45a9-82b4-57e0f27cfb5f)
![Screenshot_2024-04-10-09-26-10-40_c758632aec9121954782a375cb59c81d](https://github.com/revancedapps/revanced.net/assets/26571594/629dbc35-a2e1-4c13-ad53-a757c0e94bbd)
![Screenshot_2024-04-10-09-25-07-43_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/revancedapps/revanced.net/assets/26571594/7d2f28e4-669a-44c3-8e37-3952c2f1823f)

**Comment by SpaghettiCook** [comment]
Same issue for me. I used v5.129.3

**Comment by Ashened** [comment]
I seem to have the same problem. Have Yall fix it Yet

**Comment by majdsha** [comment]
Same here, any solutions?

**Comment by revancedapps** [comment]
Hi, due to some copyright reasons, Duolingo is preventing ReVanced from modifying its APK. Therefore, we are temporarily pausing the development of patches for Duolingo. As a result, some features may not work as expected. We will fix this in the future.
