### ISSUE TITLE
"App not installed because of incompatibility with device"

### ISSUE THREAD

**Issue by di57inct** [revancedapps/revanced.net#22]
I'm trying to update to the latest version of music extended - anddea and i get the error from the title. 
Tried both through manager and manual download from this repo.
Version 7.02.51 installed just fine.
Running a Samsung a55 with android 14 and latest one ui 6.1.

**Comment by revancedapps** [comment]
Hi, 
Could you please turn off and then turn on the "Enable Unknown Sources" setting to allow the installation of APK files? Additionally, you need to manually uninstall all versions of YT Music from your phone and try installing it again. From what I know, the Samsung A55 should be able to use Music Extended. 
If you still can't install it, you can download the version by inotia00 here: [https://revanced.net/revanced-youtube-music-extended](https://revanced.net/revanced-youtube-music-extended).

**Comment by di57inct** [comment]
tried re-enabling unknown sources. also tried deleting all and installing with the same result. it's just this latest version that has the problem. anddea's version is not the only one with this problem. all the latest music versions fail to install with the same error, both extended and "basic".

**Comment by KostromDan** [comment]
Having same issue with my new Samsung s24 ultra. Youtube ReVanced Extended - Anddea installed perfectly. Tried to install:
* ReVanced YT Music Extended Anddea
* Youtube Music Reeanced
As from manger, as from browser.
Unknown sources enabled for both.
Worked perfect on my previous phone s23 ultra.
Seems like it's this problem: https://us.community.samsung.com/t5/Galaxy-S24/S24-Ultra-has-incompatibility-with-apps/td-p/2789792

**Comment by di57inct** [comment]
v7.10.51 throwed another error when i tried to install it(package conflicts with already existing package) but i solved it by uninstalling the previous version and doing a clean install. closing this as solved for now.
