### ISSUE TITLE
No more updates for Youtube Music Revanced?

### ISSUE THREAD

**Issue by BeInvisible07** [revancedapps/revanced.net#24]
Does YT Music Revanced is sunset?
I didn't receive any updates after 7.03.52
![Screenshot_2024-07-14-17-10-26-445-edit_com revanced net revancedmanager](https://github.com/user-attachments/assets/297fb496-7f69-4df0-b21e-5ecca907c3af)

**Comment by revancedapps** [comment]
Hi, 
We will automatically update ReVanced YT Music APK based on the latest patches. This happens automatically every hour, so you won't miss any version. The ReVanced Manager app will show an update button when ReVanced supports a newer version of YT Music. This reduces the number of times you need to update the app and makes it less hassle for users with multiple versions. However, it also means that users are less likely to see updates.
![image](https://github.com/user-attachments/assets/83c85987-bdd9-46e9-9d4b-20919b389d44)

**Comment by BeInvisible07** [comment]
Bro I am asking **ReVanced YT Music Not RVX YT Music.** 
![Screenshot_2024-07-15-11-45-59-866_com android chrome](https://github.com/user-attachments/assets/3c935c0e-24e8-4e3e-b62c-ead2fe1b5936)
![Screenshot_2024-07-15-11-46-10-077_com android chrome](https://github.com/user-attachments/assets/906c1618-6667-445d-a59a-a64ff5adf83b)

**Comment by revancedapps** [comment]
yes, 7.01.52 is the highest app version that YouTube Music ReVanced supports since May.
Usually, newer versions will be updated gradually. If you want more frequent updates, please use RVX YT Music.
![image](https://github.com/user-attachments/assets/03e91f85-3175-4077-ab5a-a245b3af27e5)

**Comment by BeInvisible07** [comment]
Okay bro 👍 thank you.
