### ISSUE TITLE
Duolingo plus features

### ISSUE THREAD

**Issue by magvay** [revancedapps/revanced.net#27]
Duolingo plus features did not work
not have updates since November 2023 and v.5.129.5
(((

**Comment by tenzintrepp** [comment]
Same for me, I would be very happy if they could update it.

**Comment by Cryptnym** [comment]
I also still receive ads on version 5.129.5.
Any solution on how to switch these ads off?

**Comment by revancedapps** [comment]
Hello everyone! The Revanced Duolingo v5.158.4 update has been uploaded. The ad-blocking feature has also been [fixed](https://github.com/notjosh/revanced-patches/commit/7fbbb35a7b729214ccc6a0bebbfe1b63b1b49424), so you can now enjoy it.
